### ISSUE TITLE
Error in typo

### ISSUE THREAD

**Issue by CinquinAndy** [D-Seonay/plan-interactif#6]
When you try to register, there is an error in the {{user.getSallle}} section. 
You should try to fix that little problem ! 

https://github.com/D-Seonay/plan-interactif/blob/8a9b29b9e6180cb4c6f251ad37769fcd124cddbd/templates/registration/confirmation_register.html.twig#L10

![image](https://github.com/D-Seonay/plan-interactif/assets/55706543/ffa68715-f2c0-4524-9af9-0e9636b53c66)

**Comment by D-Seonay** [comment]
Yes, thank you, the issue has been fixed.
