### ISSUE TITLE
environement variable in public repo

### ISSUE THREAD

**Issue by LightInn** [D-Seonay/plan-interactif#7]
https://github.com/D-Seonay/plan-interactif/blob/9049c90114d2a065d76bbbecc705bd1b061384db/.env#L30

Your .env file containing sensitive information about your database connection string should not be deposited on a public repository.

**Comment by D-Seonay** [comment]
Thank you. Should the .env file also be included in the .gitignore file, since the real environment variables are used in my .env.local file?
